### ISSUE TITLE
Add instructions to run application to README.md

### ISSUE THREAD

**Issue by lynnaloo** [lynnaloo/oranjs#12]
Since this is a Node.js app, to run the application you will need to install Node.js, run `npm i` and then run the application `node index.js`. These instructions should be in the README.md.

**Comment by saksham15082** [comment]
Do we have to add this as comment or make it visible?

**Comment by saksham-s** [comment]
I had a doubt.Should we commit to master or choose the other option which says make a new branch...

**Comment by lynnaloo** [comment]
You can commit to `master` since you have a fork of this project.
