### ISSUE TITLE
Add more orange pets

### ISSUE THREAD

**Issue by lynnaloo** [lynnaloo/oranjs#3]
Create a PR (I will add the #hacktoberfest label) with pictures of orange pets for the README.md.

**Comment by zeokav** [comment]
Is that all we need to do? 😆

**Comment by lynnaloo** [comment]
I do have a standard of cuteness to uphold so don't disappoint me! 🐈

**Comment by zeokav** [comment]
Will use all my googling skills to find the cutest kitties. 😼

**Comment by banderon1** [comment]
https://github.com/lynnaloo/oranjs/pull/7

**Comment by digitalhitler** [comment]
I have two cats running around house and me everyday - Pixel & Instance - but unfortunately, they both are not orange.

**Comment by digitalhitler** [comment]
I found a solution! 

I will found **AnyJS**! 

The great idea of **AnyJS** obviously hidden in it's name: it's _better_ than _anything_. And I will tell you why.  

AnyJS can run slightly on cat of any color or colors set!

(full cat compatibility slide please)

**Comment by lynnaloo** [comment]
I support this fork of Oranjs.

**Comment by mithun-daa** [comment]
#44

**Comment by RiRam** [comment]
#49 :)

**Comment by Jedian** [comment]
Added a tiger, a red panda and a fox.

#51

**Comment by jedian** [comment]
Added a tiger, a red panda and a fox.
#51

**Comment by lynnaloo** [comment]
All of the additions look good so far. If I haven't pulled it in, then that just means they need to be merged with the existing code.
