### ISSUE TITLE
Make oran.js do something cool

### ISSUE THREAD

**Issue by lynnaloo** [lynnaloo/oranjs#5]
Basically, anything that's _simple_ and doesn't break the Travis-CI build.

**Comment by banderon1** [comment]
https://github.com/lynnaloo/oranjs/pull/8

**Comment by DeMuu** [comment]
#19

**Comment by gargi** [comment]
#23

**Comment by JakenHerman** [comment]
https://github.com/lynnaloo/oranjs/pull/34
